# Generated by Django 5.2.4 on 2025-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0002_remove_member_address_remove_member_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('farm_type', models.CharField(choices=[('Crop Farming', 'Crop Farming'), ('Livestock Farming', 'Livestock Farming'), ('Poultry Farming', 'Poultry Farming'), ('Fish Farming', 'Fish Farming'), ('Mixed Farming', 'Mixed Farming'), ('Horticulture', 'Horticulture'), ('Forestry', 'Forestry'), ('Other', 'Other')], max_length=50)),
                ('farm_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('primary_crops', models.CharField(max_length=255)),
                ('farm_location', models.TextField()),
                ('passport_photo', models.ImageField(upload_to='kyc/passport_photos/')),
                ('id_document', models.FileField(upload_to='kyc/id_documents/')),
                ('farm_photo', models.ImageField(upload_to='kyc/farm_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
