# Generated by Django 5.2.4 on 2025-07-30 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0003_kycsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='farm_location',
            new_name='farmLocation',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='farm_size',
            new_name='farmSize',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='farm_type',
            new_name='farmType',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='passport_photo',
            new_name='passportPhoto',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='primary_crops',
            new_name='primaryCrops',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='submitted_at',
            new_name='submittedAt',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='years_of_experience',
            new_name='yearsOfExperience',
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='farm_photo',
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='id_document',
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
