# Generated by Django 5.2.4 on 2025-07-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0004_rename_farm_location_kycsubmission_farmlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='membership_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
