# Generated by Django 5.2.4 on 2025-08-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0007_customuser_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='farm_description',
        ),
        migrations.RemoveField(
            model_name='member',
            name='farm_location',
        ),
        migrations.RemoveField(
            model_name='member',
            name='farm_size',
        ),
        migrations.RemoveField(
            model_name='member',
            name='farming_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='farming_years',
        ),
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='member',
            name='residential_address',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='email', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='first_name', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, default='last_name', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='lga',
            field=models.CharField(default='lga', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_id',
            field=models.CharField(blank=True, default='membership_id', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(default='state', max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
