# Generated by Django 5.2.4 on 2025-08-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0008_remove_payment_user_remove_kycsubmission_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_id',
            field=models.CharField(blank=True, default='membership_id', max_length=50, unique=True),
        ),
    ]
