# Generated by Django 5.2.4 on 2025-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0009_alter_member_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
