# Generated by Django 5.2.4 on 2025-08-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0010_alter_member_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='nin',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='kycStatus',
            field=models.CharField(default='not_submitted'),
        ),
        migrations.AddField(
            model_name='member',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
