# Generated by Django 5.2.4 on 2025-08-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0011_kycsubmission_nin_member_kycstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='kycStatus',
            field=models.CharField(default='not_submitted', max_length=20),
        ),
    ]
