# Generated by Django 5.2.4 on 2025-08-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0012_kycsubmission_kycstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='paymentStatus',
            field=models.CharField(default='not_paid'),
        ),
    ]
