# Generated by Django 5.2.4 on 2025-08-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0013_alter_member_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='paymentStatus',
            field=models.CharField(default='not_paid', max_length=20),
        ),
    ]
