# Generated by Django 5.2.4 on 2025-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0014_kycsubmission_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
