# Generated by Django 5.2.4 on 2025-08-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0015_kycsubmission_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
