# Generated by Django 5.2.4 on 2025-09-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0017_member_is_active_member_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email', max_length=254, unique=True)),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(blank=True, default='last_name', max_length=100)),
                ('state', models.CharField(default='state', max_length=100)),
                ('lga', models.CharField(default='lga', max_length=100)),
                ('sgent_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('password', models.CharField(default='password', max_length=128)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('kycStatus', models.CharField(default='not_submitted')),
                ('paymentStatus', models.CharField(default='not_paid')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
