# Generated by Django 5.2.4 on 2025-09-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0018_agentmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentmember',
            old_name='sgent_id',
            new_name='agent_id',
        ),
    ]
