# Generated by Django 5.2.4 on 2025-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0019_rename_sgent_id_agentmember_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='agent_fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='agent_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='agent_lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
