# Generated by Django 5.2.4 on 2025-09-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0020_kycsubmission_agent_fname_kycsubmission_agent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycsubmission',
            name='agent_fname',
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='agent_lname',
        ),
    ]
