# Generated by Django 5.2.4 on 2025-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0021_remove_kycsubmission_agent_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='agent_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
