# Generated by Django 5.2.4 on 2025-09-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0022_alter_kycsubmission_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
