# Generated by Django 5.2.4 on 2025-09-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0024_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='lga',
            field=models.CharField(default='lga', max_length=100),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='state',
            field=models.CharField(default='state', max_length=100),
        ),
    ]
