# Generated by Django 5.2.4 on 2025-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0026_alter_adminuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='passportPhoto',
            field=models.ImageField(upload_to='media/kyc/passport_photos/'),
        ),
    ]
