# Generated by Django 5.2.4 on 2025-09-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0027_alter_kycsubmission_passportphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='passportPhoto',
            field=models.ImageField(upload_to='kyc/passport_photos/'),
        ),
    ]
