# Generated by Django 5.2.4 on 2025-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0028_alter_kycsubmission_passportphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='passportPhoto',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
