# Generated by Django 5.2.4 on 2025-09-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0029_alter_kycsubmission_passportphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='gender',
            field=models.CharField(default='gender', max_length=11),
        ),
    ]
