# Generated by Django 5.2.4 on 2025-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0030_kycsubmission_dob_kycsubmission_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='position',
            field=models.CharField(blank=True, default='member', max_length=500, null=True),
        ),
    ]
