# Generated by Django 5.2.4 on 2025-10-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0031_kycsubmission_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='education',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='farmingCommunity',
            field=models.CharField(default='Farming community', max_length=100),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='farmingSeason',
            field=models.CharField(default='Farming season', max_length=100),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='secondaryCrops',
            field=models.CharField(default='secondary crops', max_length=255),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
