# Generated by Django 5.2.4 on 2025-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0032_kycsubmission_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='secondaryCrops',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
