# Generated by Django 5.2.4 on 2025-10-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0033_alter_kycsubmission_secondarycrops'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('agent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('gender', models.CharField(default='gender', max_length=11)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('nin', models.CharField(blank=True, default=None, max_length=11, null=True, unique=True)),
                ('education', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('position', models.CharField(blank=True, default='member', max_length=500, null=True)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('farmingCommunity', models.CharField(default='Farming community', max_length=100)),
                ('farmingSeason', models.CharField(default='Farming season', max_length=100)),
                ('farmType', models.CharField(choices=[('Crop Farming', 'Crop Farming'), ('Livestock Farming', 'Livestock Farming'), ('Poultry Farming', 'Poultry Farming'), ('Fish Farming', 'Fish Farming'), ('Mixed Farming', 'Mixed Farming'), ('Horticulture', 'Horticulture'), ('Forestry', 'Forestry'), ('Other', 'Other')], max_length=50)),
                ('farmSize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearsOfExperience', models.PositiveIntegerField()),
                ('primaryCrops', models.CharField(max_length=255)),
                ('secondaryCrops', models.CharField(blank=True, max_length=255, null=True)),
                ('farmLocation', models.TextField()),
                ('passportPhoto', models.URLField(blank=True, max_length=500, null=True)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('membership_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('kycStatus', models.CharField(default='not_submitted', max_length=20)),
                ('paymentStatus', models.CharField(default='not_paid', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
