# Generated by Django 5.2.4 on 2025-10-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0034_boa'),
    ]

    operations = [
        migrations.AddField(
            model_name='boa',
            name='BVN',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True),
        ),
    ]
