# Generated by Django 5.2.4 on 2025-10-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0035_boa_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='education',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
