# Generated by Django 5.2.4 on 2025-10-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0036_alter_kycsubmission_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='address',
            field=models.TextField(blank=True, default='address', max_length=500, null=True),
        ),
    ]
