# Generated by Django 5.2.4 on 2025-10-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0037_alter_kycsubmission_address'),
    ]

    operations = [


        migrations.AddField(
            model_name='agentmember',
            name='ward',
            field=models.CharField(default='ward', max_length=100),
        ),
    ]
