# Generated by Django 5.2.4 on 2025-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0038_agentmember_nin_agentmember_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmember',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
