# Generated by Django 5.2.4 on 2025-10-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0039_agentmember_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmember',
            name='nin',
            field=models.CharField(blank=True, default='nin', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='agentmember',
            name='phoneNumber',
            field=models.CharField(default='phoneNumber', max_length=11),
        ),
    ]
