# Generated by Django 5.2.4 on 2025-10-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0039_agentmember_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmember',
            name='nin',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agentmember',
            name='phoneNumber',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True),
        ),
    ]
