# Generated by Django 5.2.4 on 2025-10-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0040_agentmember_nin_agentmember_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmember',
            name='ward',
            field=models.CharField(blank=True, default='ward', max_length=100, null=True),
        ),
    ]
