# Generated by Django 5.2.4 on 2025-10-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0040_alter_agentmember_nin_alter_agentmember_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmember',
            name='nin',
        ),
    ]
