# Generated by Django 5.2.4 on 2025-10-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0041_remove_agentmember_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmember',
            name='nin_num',
            field=models.CharField(blank=True, default='nin', max_length=11, unique=True),
        ),
    ]
