# Generated by Django 5.2.4 on 2025-10-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0041_alter_agentmember_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmember',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmember',
            name='education',
            field=models.CharField(blank=True, default='other', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='agentmember',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=10, null=True),
        ),
    ]
