# Generated by Django 5.2.4 on 2025-10-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0042_agentmember_dob_agentmember_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmember',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='agentmember',
            name='status',
            field=models.CharField(default='not_submitted', max_length=10),
        ),
    ]
