# Generated by Django 5.2.4 on 2025-10-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0042_agentmember_dob_agentmember_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmember',
            name='approval_status',
            field=models.CharField(blank=True, default='Suspended', max_length=100),
        ),
    ]
