# Generated by Django 5.2.4 on 2025-10-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0043_alter_agentmember_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmember',
            name='gender',
            field=models.CharField(blank=True, default='gender', max_length=10, null=True),
        ),
    ]
