# Generated by Django 5.2.4 on 2025-10-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0043_remove_agentmember_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmember',
            name='status',
            field=models.CharField(blank=True, default='Suspended', max_length=100),
        ),
    ]
