# Generated by Django 5.2.4 on 2025-10-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0044_alter_agentmember_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmember',
            name='approval_status',
            field=models.CharField(blank=True, default='pending', max_length=100),
        ),
    ]
