# Generated by Django 5.2.4 on 2025-10-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0044_remove_agentmember_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmember',
            name='nin',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
