# Generated by Django 5.2.4 on 2025-10-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0045_agentmember_nin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmember',
            name='nin',
        ),
    ]
