# Generated by Django 5.2.4 on 2025-10-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0045_alter_agentmember_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmember',
            name='education',
            field=models.CharField(blank=True, default='education', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentmember',
            name='gender',
            field=models.CharField(blank=True, default='gender', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentmember',
            name='phoneNumber',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, unique=True),
        ),
    ]
