# Generated by Django 5.2.4 on 2025-10-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0045_alter_agentmember_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmember',
            name='status',
        ),
        migrations.AddField(
            model_name='agentmember',
            name='approval_status',
            field=models.CharField(blank=True, default='Suspended', max_length=100),
        ),
    ]
