# Generated by Django 5.2.4 on 2025-10-16 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0046_remove_agentmember_nin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmember',
            name='phoneNumber',
        ),
    ]
