# Generated by Django 5.2.4 on 2025-10-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0046_alter_agentmember_education_alter_agentmember_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmember',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentmember',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
