# Generated by Django 5.2.4 on 2025-10-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0047_remove_agentmember_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmember',
            name='NIN',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True),
        ),
    ]
