# Generated by Django 5.2.4 on 2025-10-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0047_agentmember_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='farmAssociation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='farmCoordinates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='farmDocument',
            field=models.TextField(blank=True, null=True),
        ),
    ]
