# Generated by Django 5.2.4 on 2025-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0048_kycsubmission_farmassociation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='farmLocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='farmSize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='farmType',
            field=models.CharField(blank=True, choices=[('Crop Farming', 'Crop Farming'), ('Livestock Farming', 'Livestock Farming'), ('Poultry Farming', 'Poultry Farming'), ('Fish Farming', 'Fish Farming'), ('Mixed Farming', 'Mixed Farming'), ('Horticulture', 'Horticulture'), ('Forestry', 'Forestry'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='farmingCommunity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='farmingSeason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='gender',
            field=models.CharField(blank=True, default='Not specified', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='kycStatus',
            field=models.CharField(blank=True, default='not_submitted', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='paymentStatus',
            field=models.CharField(blank=True, default='not_paid', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='position',
            field=models.CharField(blank=True, default='member', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='primaryCrops',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='yearsOfExperience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
