# Generated by Django 5.2.4 on 2025-10-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0048_agentmember_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmember',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True),
        ),
    ]
