# Generated by Django 5.2.4 on 2025-10-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0049_agentmember_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmember',
            name='NIN',
        ),
        migrations.AddField(
            model_name='agentmember',
            name='NINNUM',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, unique=True),
        ),
    ]
