# Generated by Django 5.2.4 on 2025-10-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afan_backend_app', '0050_remove_agentmember_nin_agentmember_ninnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentmember',
            old_name='NINNUM',
            new_name='nin',
        ),
        migrations.RenameField(
            model_name='agentmember',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
